language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build:webpack
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: main